# permissions for end users to view staticwebsites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: staticwebsite-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: static-website-operator
    app.kubernetes.io/part-of: static-website-operator
    app.kubernetes.io/managed-by: kustomize
  name: staticwebsite-viewer-role
rules:
- apiGroups:
  - websites.example.com
  resources:
  - staticwebsites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - websites.example.com
  resources:
  - staticwebsites/status
  verbs:
  - get
